# Base SonarQube configuration for City of Helsinki Frontend projects
sonar.projectKey = City-of-Helsinki_kukkuu-admin
sonar.organization = city-of-helsinki
sonar.javascript.lcov.reportPaths = ./coverage/lcov.info
sonar.sourceEncoding = UTF-8
sonar.sources = src

# kukkuu-admin specific
sonar.javascript.node.maxspace = 8192

sonar.exclusions = \
  **/__tests__/**/*, \
  **/__mocks__/**/*, \
  **/__snapshots__/*, \
  **/*.d.ts, \
  **/*.test.js, \
  **/*.test.ts, \
  **/*.test.jsx, \
  **/*.test.tsx, \
  **/*.spec.js, \
  **/*.spec.ts, \
  **/*.spec.jsx, \
  **/*.spec.tsx, \
  src/setupTests.js, \
  src/setupTests.ts, \
  src/domain/api/generatedTypes/**

sonar.coverage.exclusions = \
  **/*.stories.js, \
  **/*.stories.ts, \
  **/*.stories.jsx, \
  **/*.stories.tsx, \
  src/index.js, \
  src/index.jsx, \
  src/index.ts, \
  src/index.tsx, \
  src/serviceWorker.js, \
  src/serviceWorker.ts, \
  src/domain/children/api/ChildApi.ts, \
  src/domain/dashboard/api.ts, \
  src/domain/eventGroups/api/eventGroupsApi.ts, \
  src/domain/events/api/EventApi.ts, \
  src/domain/eventsAndEventGroups/api/eventsAndEventGroupsApi.ts, \
  src/domain/messages/api/messagesApi.ts, \
  src/domain/occurrences/api/OccurrenceApi.ts, \
  src/domain/profile/api.ts, \
  src/domain/ticketSystemPassword/api/ticketSystemPasswordsApi.ts, \
  src/domain/venues/api/VenueApi.ts, \
  **/mutations/**, \
  **/queries/**

sonar.test.inclusions = \
  **/__tests__/**/*, \
  **/*.test.js, \
  **/*.test.ts, \
  **/*.test.jsx, \
  **/*.test.tsx, \
  **/*.spec.js, \
  **/*.spec.ts, \
  **/*.spec.jsx, \
  **/*.spec.tsx
