name: Browser tests

on:
  schedule:
    # Every weekday (Mon-Fri) at 9 in the morning
    - cron: '0 9 * * 1-5'
  workflow_dispatch:

jobs:
  browser_test:
    name: Browser tests

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Install dependencies
      uses: bahmutov/npm-install@v1
    - name: Run browser tests against staging server
      run: yarn test:browser:ci
      env:
        BROWSER_TESTS_ENV_URL: https://kukkuu-admin.test.kuva.hel.ninja
        BROWSER_TESTS_UID: ${{ secrets.BROWSER_TESTS_UID }}
        BROWSER_TESTS_PWD: ${{ secrets.BROWSER_TESTS_PWD }}
